
const SIGNED_IN = 'eoh/user/SIGNED_IN';
const SIGNED_OUT = 'eoh/user/SIGNED_OUT';

const SHOW_NEED_TO_SIGN_IN_WARNING = 'eoh/user/SHOW_NEED_TO_SIGN_IN_WARNING';
const HIDE_NEED_TO_SIGN_IN_WARNING = 'eoh/user/HIDE_NEED_TO_SIGN_IN_WARNING';

const SHOW_SESSION_EXPIRED_WARNING = 'eoh/user/SHOW_SESSION_EXPIRED_WARNING';
const HIDE_SESSION_EXPIRED_WARNING = 'eoh/user/HIDE_SESSION_EXPIRED_WARNING';

const DEBOUNCE_SAFETY_START = 'eoh/user/DEBOUNCE_SAFETY_START';
const DEBOUNCE_SAFETY_END = 'eoh/user/DEBOUNCE_SAFETY_END';

export default {
  SIGNED_IN,
  SIGNED_OUT,
  SHOW_NEED_TO_SIGN_IN_WARNING,
  HIDE_NEED_TO_SIGN_IN_WARNING,
  SHOW_SESSION_EXPIRED_WARNING,
  HIDE_SESSION_EXPIRED_WARNING,
  DEBOUNCE_SAFETY_START,
  DEBOUNCE_SAFETY_END,
};
