
const SHOW_NETWORK_WARNING = 'eoh/user/SHOW_NETWORK_WARNING';
const HIDE_NETWORK_WARNING = 'eoh/user/HIDE_NETWORK_WARNING';

const DEBOUNCE_SAFETY_START = 'eoh/user/DEBOUNCE_SAFETY_START';
const DEBOUNCE_SAFETY_END = 'eoh/user/DEBOUNCE_SAFETY_END';

export default {
  SHOW_NETWORK_WARNING,
  HIDE_NETWORK_WARNING,
  
  DEBOUNCE_SAFETY_START,
  DEBOUNCE_SAFETY_END,
};
