
const LOADING_IN_PROGRESS = 'eoh/articles/LOADING_IN_PROGRESS';
const LOADING_FAILED = 'eoh/articles/LOADING_FAILED';
const LOADING_SUCCESS = 'eoh/articles/LOADING_SUCCESS';

const MORE_IN_PROGRESS = 'eoh/articles/MORE_IN_PROGRESS';
const MORE_FAILED = 'eoh/articles/MORE_FAILED';
const MORE_SUCCESS = 'eoh/articles/MORE_SUCCESS';

const ON_ADDING_ATTRIBUTE_VALUE_VALID_CHECKING_IN_PROGRESS = 'eoh/articles/ON_ADDING_ATTRIBUTE_VALUE_VALID_CHECKING_IN_PROGRESS';
const ON_ADDING_ATTRIBUTE_VALUE_VALID = 'eoh/articles/ON_ADDING_ATTRIBUTE_VALUE_VALID';
const ON_ADDING_ATTRIBUTE_VALUE_INVALID = 'eoh/articles/ON_ADDING_ATTRIBUTE_VALUE_INVALID';

const ON_ADDING_ATTRIBUTE_STARTED = 'eoh/articles/ON_ADDING_STARTED';
const ON_ADD_ATTRIBUTE_SUCCESSFUL = 'eoh/articles/ON_ADD_ATTRIBUTE_SUCCESSFUL';
const ON_ADD_ATTRIBUTE_FAILED_INVALID_VALUE = 'eoh/articles/ON_ADD_ATTRIBUTE_FAILED_INVALID_VALUE';
const ON_ADD_ATTRIBUTE_FAILED_AUTHENTICATION = 'eoh/articles/ON_ADD_ATTRIBUTE_FAILED_AUTHENTICATION';
const ON_ADD_ATTRIBUTE_FAILED_OTHER_REASON = 'eoh/articles/ON_ADD_ATTRIBUTE_FAILED_OTHER_REASON';

const SHOW_MORE_ATTRIBUTES_IN_PROGRESS = 'eoh/articles/SHOW_MORE_ATTRIBUTES_IN_PROGRESS';
const SHOW_MORE_ATTRIBUTES_FAILED = 'eoh/articles/SHOW_MORE_ATTRIBUTES_FAILED';
const SHOW_MORE_ATTRIBUTES_SUCCESS = 'eoh/articles/SHOW_MORE_ATTRIBUTES_SUCCESS';

const ON_SCORE_UPDATED = 'eoh/articles/ON_SCORE_UPDATED';

export default {
  LOADING_IN_PROGRESS,
  LOADING_FAILED,
  LOADING_SUCCESS,

  MORE_IN_PROGRESS,
  MORE_FAILED,
  MORE_SUCCESS,

  ON_ADDING_ATTRIBUTE_VALUE_VALID_CHECKING_IN_PROGRESS,
  ON_ADDING_ATTRIBUTE_VALUE_VALID,
  ON_ADDING_ATTRIBUTE_VALUE_INVALID,

  ON_ADDING_ATTRIBUTE_STARTED,
  ON_ADD_ATTRIBUTE_SUCCESSFUL,
  ON_ADD_ATTRIBUTE_FAILED_INVALID_VALUE,
  ON_ADD_ATTRIBUTE_FAILED_AUTHENTICATION,
  ON_ADD_ATTRIBUTE_FAILED_OTHER_REASON,

  SHOW_MORE_ATTRIBUTES_IN_PROGRESS,
  SHOW_MORE_ATTRIBUTES_FAILED,
  SHOW_MORE_ATTRIBUTES_SUCCESS,

  ON_SCORE_UPDATED,
};
